- hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: installing docker dependencies
    remote_user: content
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  - name: add dockers official GPG key
    remote_user: content
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: verify that we have the key with the fingerprint
    remote_user: content
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: set up the stable repository
    remote_user: content
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: update apt packages
    remote_user: content
    apt:
      update_cache: yes
    tags:
      - docker
  - name: install docker
    remote_user: content
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
      - docker
  - name: add remote "content" user to "docker" group
    remote_user: content
    user:
      name: "content"
      group: "docker"
      append: yes
    tags:
      - docker
  - name: install docker-compose
    remote_user: content
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'