- hosts: all
  gather_facts: true
  become: true
  become_user: "content"

  pre_tasks:
    - name: update repositories
      remote_user: content
      apt: update_cache=yes
      become_method: sudo
      become_user: content
      changed_when: False
  vars:
    user: "content"
  tasks:
  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: true

  - name: downloadint installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust